import { Plus, Users } from "lucide-react";
import { EmptyState, EmptyTableRow } from "@/components/dashboard/EmptyState";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { StatusBadge } from "@/components/dashboard/StatusBadge";
import { StatefulForm } from "@/components/forms/StatefulForm";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { requireBusinessUser } from "@/lib/auth";
import { getSportsPlayers } from "@/lib/sports-data";
import { saveSportsPlayerAction } from "@/lib/sports-actions";

export default async function PlayersPage() {
  const user = await requireBusinessUser();
  if (user.business.businessType.code !== "SPORTS_CLUB") return <><PageHeader eyebrow="Club roster" title="Players" description="Player management is available for Sports Club workspaces." /><EmptyState title="Not enabled for this workspace" description="Players are part of the Sports Club module." /></>;
  const players = await getSportsPlayers(user.business.id);
  return <><PageHeader eyebrow="Club roster" title="Players" description="Player profiles connect family contacts, rosters, documents, recruiting, and payment history." />
    <div className="grid cols-3"><section className="panel" style={{ gridColumn: "span 2" }}><div className="panel-header"><div><h2>Player directory</h2><p>{players.length} player profiles scoped to {user.business.name}.</p></div><Users size={20} /></div><div className="panel-body table-wrap"><table className="data-table"><thead><tr><th>Player</th><th>Family</th><th>Position</th><th>Team</th><th>Status</th><th>Grad</th></tr></thead><tbody>{players.length ? players.map((player) => <tr key={player.id}><td><strong>{player.firstName} {player.lastName}</strong><div style={{ color: "var(--muted)", marginTop: 4 }}>{player.jerseyNumber ? `#${player.jerseyNumber}` : "No jersey number"}</div></td><td>{player.family.familyName}<div style={{ color: "var(--muted)", marginTop: 4 }}>{player.family.customer.email}</div></td><td>{player.positions.join(", ") || "Not set"}</td><td>{player.rosters.filter((roster) => roster.status === "ACTIVE").map((roster) => roster.team.name).join(", ") || "Unassigned"}</td><td><StatusBadge status={player.status} /></td><td>{player.graduationYear ?? "-"}</td></tr>) : <EmptyTableRow columns={6} message="No players have been added yet." />}</tbody></table></div></section>
      <section className="panel"><div className="panel-header"><div><h2>Add player</h2><p>Create a player profile and the connected family CRM record.</p></div><Plus size={20} /></div><div className="panel-body"><StatefulForm action={saveSportsPlayerAction}><div className="field"><label htmlFor="firstName">Player first name</label><input className="input" id="firstName" name="firstName" required /></div><div className="field"><label htmlFor="lastName">Player last name</label><input className="input" id="lastName" name="lastName" required /></div><div className="field"><label htmlFor="familyName">Family last name</label><input className="input" id="familyName" name="familyName" required /></div><div className="field"><label htmlFor="parentName">Parent / billing contact</label><input className="input" id="parentName" name="parentName" required /></div><div className="field"><label htmlFor="parentEmail">Parent email</label><input className="input" id="parentEmail" name="parentEmail" type="email" required /></div><div className="field"><label htmlFor="parentPhone">Parent phone</label><input className="input" id="parentPhone" name="parentPhone" /></div><div className="form-grid"><div className="field"><label htmlFor="graduationYear">Grad year</label><input className="input" id="graduationYear" name="graduationYear" type="number" min="2024" max="2045" /></div><div className="field"><label htmlFor="jerseyNumber">Jersey #</label><input className="input" id="jerseyNumber" name="jerseyNumber" /></div></div><div className="field"><label htmlFor="positions">Positions</label><input className="input" id="positions" name="positions" placeholder="Pitcher, Shortstop" /></div><div className="field"><label htmlFor="status">Status</label><select className="select" id="status" name="status" defaultValue="PROSPECT"><option value="PROSPECT">Prospect</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="GRADUATED">Graduated</option></select></div><div className="field"><label htmlFor="notes">Notes</label><textarea className="textarea" id="notes" name="notes" /></div><SubmitButton><Plus size={16} />Add player</SubmitButton></StatefulForm></div></section></div></>;
}
