import { ClipboardPenLine, ExternalLink, Plus } from "lucide-react";
import { EmptyState, EmptyTableRow } from "@/components/dashboard/EmptyState";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { StatusBadge } from "@/components/dashboard/StatusBadge";
import { StatefulForm } from "@/components/forms/StatefulForm";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { requireBusinessUser } from "@/lib/auth";
import { getSportsForms } from "@/lib/sports-data";
import { saveSportsFormAction } from "@/lib/sports-actions";
import { formatCurrency } from "@/lib/format";

export default async function FormsPage() {
  const user = await requireBusinessUser(); if (user.business.businessType.code !== "SPORTS_CLUB") return <><PageHeader eyebrow="Club intake" title="Forms & waivers" description="Club forms are part of Sports Club operations." /><EmptyState title="Not enabled for this workspace" description="Forms are only available for club workspaces." /></>;
  const forms = await getSportsForms(user.business.id);
  return <><PageHeader eyebrow="Club intake" title="Forms & waivers" description="Create shareable intake forms for tryouts, registration, medical records, waivers, volunteers, and sponsor inquiries." /><div className="grid cols-3"><section className="panel" style={{ gridColumn: "span 2" }}><div className="panel-header"><div><h2>Shareable forms</h2><p>Form submissions create a linked parent CRM record, family, and player prospect where appropriate.</p></div><ClipboardPenLine size={20} /></div><div className="panel-body table-wrap"><table className="data-table"><thead><tr><th>Form</th><th>Type</th><th>Fee</th><th>Submissions</th><th>Status</th><th></th></tr></thead><tbody>{forms.length ? forms.map((form) => <tr key={form.id}><td><strong>{form.title}</strong><div style={{ color: "var(--muted)", marginTop: 4 }}>{form.description ?? "No description"}</div></td><td><StatusBadge status={form.type} /></td><td>{formatCurrency(form.fee)}</td><td>{form.submissions.length}</td><td><StatusBadge status={form.active ? "ACTIVE" : "INACTIVE"} /></td><td><a className="button ghost" href={`/club/${user.business.slug}/forms/${form.slug}`} target="_blank" rel="noreferrer"><ExternalLink size={14} />Open</a></td></tr>) : <EmptyTableRow columns={6} message="No club forms have been created yet." />}</tbody></table></div></section><section className="panel"><div className="panel-header"><div><h2>Create form</h2><p>Standard parent/player fields are included. Custom field builder is intentionally deferred.</p></div><Plus size={20} /></div><div className="panel-body"><StatefulForm action={saveSportsFormAction}><div className="field"><label htmlFor="title">Title</label><input className="input" id="title" name="title" placeholder="2026 Ghost Baseball Tryouts" required /></div><div className="field"><label htmlFor="type">Type</label><select className="select" id="type" name="type"><option value="TRYOUT">Tryout registration</option><option value="PLAYER_REGISTRATION">Player registration</option><option value="MEDICAL">Medical form</option><option value="WAIVER">Waiver</option><option value="VOLUNTEER">Volunteer form</option><option value="SPONSOR_INQUIRY">Sponsor inquiry</option></select></div><div className="field"><label htmlFor="description">Description</label><textarea className="textarea" id="description" name="description" /></div><div className="field"><label htmlFor="fee">Registration fee</label><input className="input" id="fee" name="fee" type="number" min="0" step="0.01" defaultValue="0" /></div><SubmitButton><Plus size={16} />Create form</SubmitButton></StatefulForm></div></section></div></>;
}
