import { Handshake, Plus } from "lucide-react";
import { EmptyState, EmptyTableRow } from "@/components/dashboard/EmptyState";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { StatusBadge } from "@/components/dashboard/StatusBadge";
import { StatefulForm } from "@/components/forms/StatefulForm";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { requireBusinessUser } from "@/lib/auth";
import { getSponsors } from "@/lib/sports-data";
import { saveSponsorAction } from "@/lib/sports-actions";

export default async function SponsorsPage() {
  const user = await requireBusinessUser(); if (user.business.businessType.code !== "SPORTS_CLUB") return <><PageHeader eyebrow="Club growth" title="Sponsors" description="Sponsor management is part of Sports Club operations." /><EmptyState title="Not enabled for this workspace" description="Sponsors are only available for club workspaces." /></>;
  const sponsors = await getSponsors(user.business.id);
  return <><PageHeader eyebrow="Club growth" title="Sponsors" description="Track sponsor prospects and partners alongside the club’s relationship history." /><div className="grid cols-3"><section className="panel" style={{ gridColumn: "span 2" }}><div className="panel-header"><div><h2>Sponsor pipeline</h2><p>{sponsors.length} club partnerships and prospects.</p></div><Handshake size={20} /></div><div className="panel-body table-wrap"><table className="data-table"><thead><tr><th>Sponsor</th><th>Contact</th><th>Tier</th><th>Status</th><th>Notes</th></tr></thead><tbody>{sponsors.length ? sponsors.map((sponsor) => <tr key={sponsor.id}><td><strong>{sponsor.name}</strong></td><td>{sponsor.contactName ?? sponsor.email ?? "-"}</td><td>{sponsor.tier ?? "-"}</td><td><StatusBadge status={sponsor.status} /></td><td>{sponsor.notes ?? "-"}</td></tr>) : <EmptyTableRow columns={5} message="No sponsors have been added yet." />}</tbody></table></div></section><section className="panel"><div className="panel-header"><div><h2>Add sponsor</h2><p>Capture the relationship now; sponsorship packages can follow.</p></div><Plus size={20} /></div><div className="panel-body"><StatefulForm action={saveSponsorAction}><div className="field"><label htmlFor="name">Organization</label><input className="input" id="name" name="name" required /></div><div className="field"><label htmlFor="contactName">Contact</label><input className="input" id="contactName" name="contactName" /></div><div className="field"><label htmlFor="email">Email</label><input className="input" id="email" name="email" type="email" /></div><div className="field"><label htmlFor="tier">Tier</label><input className="input" id="tier" name="tier" placeholder="Gold" /></div><div className="field"><label htmlFor="status">Status</label><select className="select" id="status" name="status"><option>Prospect</option><option>Contacted</option><option>Partner</option><option>Renewal</option></select></div><div className="field"><label htmlFor="notes">Notes</label><textarea className="textarea" id="notes" name="notes" /></div><SubmitButton><Plus size={16} />Add sponsor</SubmitButton></StatefulForm></div></section></div></>;
}
