import { BarChart3 } from "lucide-react";
import { EmptyState } from "@/components/dashboard/EmptyState";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { requireBusinessUser } from "@/lib/auth";
import { getSportsOverview } from "@/lib/sports-data";
import { formatCurrency } from "@/lib/format";

export default async function ReportsPage() {
  const user = await requireBusinessUser(); if (user.business.businessType.code !== "SPORTS_CLUB") return <><PageHeader eyebrow="Club reporting" title="Reports" description="Club reporting is part of Sports Club operations." /><EmptyState title="Not enabled for this workspace" description="Reports are only available for club workspaces." /></>;
  const data = await getSportsOverview(user.business.id); const paid = data.invoices.filter((invoice) => invoice.status === "PAID"); const pastDue = data.invoices.filter((invoice) => invoice.status === "PAST_DUE");
  return <><PageHeader eyebrow="Club reporting" title="Reports" description="A practical internal read on player participation, tryouts, team capacity, club revenue, and payment aging." /><div className="grid cols-4"><section className="panel metric-card"><span className="metric-label">Active players</span><strong className="metric-value">{data.activePlayers}</strong><span className="metric-delta">Current player status</span></section><section className="panel metric-card"><span className="metric-label">Tryouts</span><strong className="metric-value">{data.tryouts.length}</strong><span className="metric-delta">Recent submissions</span></section><section className="panel metric-card"><span className="metric-label">Revenue</span><strong className="metric-value">{formatCurrency(data.collected)}</strong><span className="metric-delta">Paid invoices</span></section><section className="panel metric-card"><span className="metric-label">Payment aging</span><strong className="metric-value">{pastDue.length}</strong><span className="metric-delta">Past-due invoices</span></section></div><div className="grid cols-2" style={{ marginTop: 16 }}><section className="panel"><div className="panel-header"><div><h2>Team sizes</h2><p>Active roster counts by current team.</p></div><BarChart3 size={20} /></div><div className="panel-body timeline-list">{data.teams.length ? data.teams.map((team) => <article className="timeline-item" key={team.id}><div><strong>{team.name}</strong><span>{team.rosters.length} active players</span></div><p>{team.ageGroup} · {team.season}</p></article>) : <EmptyState title="No teams yet" description="Create club teams to see roster sizing." />}</div></section><section className="panel"><div className="panel-header"><div><h2>Payment summary</h2><p>Use Communications to send payment reminders to family segments.</p></div></div><div className="panel-body timeline-list"><article className="timeline-item"><div><strong>Paid invoices</strong><span>{paid.length}</span></div><p>{formatCurrency(paid.reduce((sum, invoice) => sum + Number(invoice.amount), 0))} collected</p></article><article className="timeline-item"><div><strong>Outstanding invoices</strong><span>{data.openBalances.length}</span></div><p>{formatCurrency(data.openBalances.reduce((sum, invoice) => sum + Number(invoice.amount), 0))} due</p></article></div></section></div></>;
}
