import { Plus, ShieldCheck } from "lucide-react";
import { EmptyState, EmptyTableRow } from "@/components/dashboard/EmptyState";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { StatusBadge } from "@/components/dashboard/StatusBadge";
import { StatefulForm } from "@/components/forms/StatefulForm";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { requireBusinessUser } from "@/lib/auth";
import { getSportsCoaches } from "@/lib/sports-data";
import { saveSportsCoachAction } from "@/lib/sports-actions";

export default async function CoachesPage() {
  const user = await requireBusinessUser(); if (user.business.businessType.code !== "SPORTS_CLUB") return <><PageHeader eyebrow="Club staff" title="Coaches" description="Coach management is part of Sports Club operations." /><EmptyState title="Not enabled for this workspace" description="Coaches are only available for club workspaces." /></>;
  const coaches = await getSportsCoaches(user.business.id);
  return <><PageHeader eyebrow="Club staff" title="Coaches" description="Keep assignments, certifications, and background-check status beside each team." /><div className="grid cols-3"><section className="panel" style={{ gridColumn: "span 2" }}><div className="panel-header"><div><h2>Coaching staff</h2><p>{coaches.length} coach records scoped to the club.</p></div><ShieldCheck size={20} /></div><div className="panel-body table-wrap"><table className="data-table"><thead><tr><th>Coach</th><th>Contact</th><th>Assigned teams</th><th>Certifications</th><th>Background check</th></tr></thead><tbody>{coaches.length ? coaches.map((coach) => <tr key={coach.id}><td><strong>{coach.name}</strong></td><td>{coach.email ?? coach.phone ?? "Not set"}</td><td>{coach.assignments.map((assignment) => assignment.team.name).join(", ") || "Unassigned"}</td><td>{coach.certifications ?? "Not recorded"}</td><td><StatusBadge status={coach.backgroundCheckStatus} /></td></tr>) : <EmptyTableRow columns={5} message="No coaches have been added yet." />}</tbody></table></div></section><section className="panel"><div className="panel-header"><div><h2>Add coach</h2><p>Coach records can be connected to teams from Teams.</p></div><Plus size={20} /></div><div className="panel-body"><StatefulForm action={saveSportsCoachAction}><div className="field"><label htmlFor="name">Name</label><input className="input" id="name" name="name" required /></div><div className="field"><label htmlFor="email">Email</label><input className="input" id="email" name="email" type="email" /></div><div className="field"><label htmlFor="phone">Phone</label><input className="input" id="phone" name="phone" /></div><div className="field"><label htmlFor="certifications">Certifications</label><input className="input" id="certifications" name="certifications" placeholder="USA Baseball, CPR" /></div><div className="field"><label htmlFor="backgroundCheckStatus">Background check</label><select className="select" id="backgroundCheckStatus" name="backgroundCheckStatus"><option>Pending</option><option>Complete</option><option>Expired</option></select></div><div className="field"><label htmlFor="notes">Notes</label><textarea className="textarea" id="notes" name="notes" /></div><SubmitButton><Plus size={16} />Add coach</SubmitButton></StatefulForm></div></section></div></>;
}
