import { CalendarClock, Plus } from "lucide-react";
import { EmptyState, EmptyTableRow } from "@/components/dashboard/EmptyState";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { StatusBadge } from "@/components/dashboard/StatusBadge";
import { StatefulForm } from "@/components/forms/StatefulForm";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { requireBusinessUser } from "@/lib/auth";
import { getSportsSchedule, getSportsTeams } from "@/lib/sports-data";
import { saveSportsScheduleAction } from "@/lib/sports-actions";
import { formatDate } from "@/lib/format";

export default async function SchedulePage() {
  const user = await requireBusinessUser(); if (user.business.businessType.code !== "SPORTS_CLUB") return <><PageHeader eyebrow="Club calendar" title="Schedule" description="Schedules are part of Sports Club operations." /><EmptyState title="Not enabled for this workspace" description="Schedules are only available for club workspaces." /></>;
  const [events, teams] = await Promise.all([getSportsSchedule(user.business.id), getSportsTeams(user.business.id)]);
  return <><PageHeader eyebrow="Club calendar" title="Schedule" description="One list for practice cadence, opponents, tournament weekends, tryouts, and club events." /><div className="grid cols-3"><section className="panel" style={{ gridColumn: "span 2" }}><div className="panel-header"><div><h2>Upcoming calendar</h2><p>{events.length} scheduled club moments.</p></div><CalendarClock size={20} /></div><div className="panel-body table-wrap"><table className="data-table"><thead><tr><th>Event</th><th>Team</th><th>When</th><th>Location</th><th>Opponent</th></tr></thead><tbody>{events.length ? events.map((event) => <tr key={event.id}><td><strong>{event.title}</strong><div style={{ marginTop: 4 }}><StatusBadge status={event.type} /></div></td><td>{event.team?.name ?? "Club-wide"}</td><td>{formatDate(event.startsAt)}</td><td>{event.location ?? "TBD"}</td><td>{event.opponent ?? "-"}</td></tr>) : <EmptyTableRow columns={5} message="No scheduled events yet." />}</tbody></table></div></section><section className="panel"><div className="panel-header"><div><h2>Add event</h2><p>Use Communications for the related reminder or update.</p></div><Plus size={20} /></div><div className="panel-body"><StatefulForm action={saveSportsScheduleAction}><div className="field"><label htmlFor="title">Title</label><input className="input" id="title" name="title" placeholder="12U practice" required /></div><div className="field"><label htmlFor="type">Type</label><select className="select" id="type" name="type"><option value="PRACTICE">Practice</option><option value="GAME">Game</option><option value="TOURNAMENT">Tournament</option><option value="TRYOUT">Tryout</option><option value="CLUB_EVENT">Club event</option></select></div><div className="field"><label htmlFor="startsAt">Date/time</label><input className="input" id="startsAt" name="startsAt" type="datetime-local" required /></div><div className="field"><label htmlFor="teamId">Team</label><select className="select" id="teamId" name="teamId"><option value="">Club-wide</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></div><div className="field"><label htmlFor="location">Location</label><input className="input" id="location" name="location" /></div><div className="field"><label htmlFor="opponent">Opponent</label><input className="input" id="opponent" name="opponent" /></div><div className="field"><label htmlFor="description">Description</label><textarea className="textarea" id="description" name="description" /></div><SubmitButton><Plus size={16} />Add event</SubmitButton></StatefulForm></div></section></div></>;
}
